# = jetty_path key
# each environment can have a jetty_path with absolute or relative
# (to app root) path to a jetty/solr install. This is used
# by the rake tasks that start up solr automatically for testing
# and by rake solr:marc:index.
#
# jetty_path is not used by a running Blacklight application
# at all. In general you do NOT need to deploy solr in Jetty, you can deploy it
# however you want.
# jetty_path is only required for rake tasks that need to know
# how to start up solr, generally for automated testing.

default: &default
  url: <%= Rails.application.secrets.solr_url %>
development:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/discovery' %>
test: &test
  url: http://localhost:8983/solr/discovery-test
  writable: true
ingest: 
  <<: *default
  writable: true
production:
  <<: *default
