# *** WARNING *** 
# Ansible contains customized copies of this file, for Test & Prod environments.
# Why? Specifically, to address the changing URL for solr, and Neil's inability to
# use lineinfile to achieve the desired results.

solr: http://localhost:8983/solr

proxy: http://login.ezproxy.library.ualberta.ca/login?url=

collections: ["peel", "sfx", "symphony", "maps", "era", "era_test", "sfx_test", "databases"]

era:
   schema: dublin_core
   root: "//xmlns:OAI-PMH"
   delimiter: "//xmlns:record"
   namespace: '{"xmlns" => "http://www.openarchives.org/OAI/2.0/"}'
   vocabulary: DublinCoreVocabulary
   endpoint: "http://era.library.ualberta.ca/oaiprovider/?verb=ListRecords&metadataPrefix=oai_dc"
   mode: file
   path: "data/era.xml"

era_test:
   schema: dublin_core
   root: "//xmlns:OAI-PMH"
   delimiter: "//xmlns:record"
   namespace: '{"xmlns" => "http://www.openarchives.org/OAI/2.0/"}'
   vocabulary: DublinCoreVocabulary
   mode: file
   path: "data/era.xml"

peel:
  schema: mods
  root: "//xmlns:mods"
  delimiter: "//xmlns:mods"
  namespace: '{"xmlns" => "http://www.loc.gov/mods/v3"}'
  vocabulary: PeelModsVocabulary
  mode: directory
  path: "data/peel_mods_xml/"

sfx:
  schema: marc
  config: "config/SolrMarc/sfx_config.properties"
  endpoint: "http://resolver.library.ualberta.ca/sfx2sirsi/data/sfxdata.xml"
  path: "data/sfx.xml"

sfx_test:
  config: "config/SolrMarc/sfx_config.properties"
  schema: marc
  path: "data/sfx.xml"

symphony:
  config: "config/SolrMarc/symphony_config.properties"
  schema: marc
  path: "data/sample.mrc"

maps:
  schema: marc
  path: "data/maps.xml"

cihm:
  schema: marc
  path: "data/cihm.mrc"

curriculum:
  schema: mods
  root: "//mods:modsCollection"
  delimiter: "//mods:mods"
  namespace: '{"mods" => "http://www.loc.gov/mods/v3"}'
  vocabulary: CurriculumModsVocabulary
  mode: file
  path: "data/curriculummods.xml"

databases:
  schema: database
  root: "//databases"
  delimiter: "//database"
  namespace: ""
  vocabulary: DatabaseVocabulary
  mode: file
  expand_path: "data/databases.xml"
  path: "data/databases.csv"
  endpoint: http://www.library.ualberta.ca/batchjobs/SFX/dbMetadata/dbdump_csv.php
