solr: http://solr:8983/solr/discovery

proxy: http://login.ezproxy.library.ualberta.ca/login?url=

collections: ["peel", "sfx", "symphony", "maps", "era", "era_test", "sfx_test", "databases", "services", "database_test_set", "sfx_test_set", "symphony_test_set", "symphony_test_deletes", "kule"]

era:
  schema: dublin_core
  root: "//xmlns:OAI-PMH"
  delimiter: "//xmlns:record"
  namespace: '{"xmlns" => "http://www.openarchives.org/OAI/2.0/"}'
  vocabulary: DublinCoreVocabulary
  endpoint: "http://era.library.ualberta.ca/oaiprovider/?verb=ListRecords&metadataPrefix=oai_dc"
  mode: file
  path: "data/era.xml"

era_test:
  schema: dublin_core
  root: "//xmlns:OAI-PMH"
  delimiter: "//xmlns:record"
  namespace: '{"xmlns" => "http://www.openarchives.org/OAI/2.0/"}'
  vocabulary: DublinCoreVocabulary
  mode: file
  path: "data/era.xml"

peel:
  schema: mods
  root: "//xmlns:mods"
  delimiter: "//xmlns:mods"
  namespace: '{"xmlns" => "http://www.loc.gov/mods/v3"}'
  vocabulary: PeelModsVocabulary
  mode: directory
  path: "data/peel_mods_xml/"

sfx:
  schema: marc
  config: "config/SolrMarc/sfx_config.properties"
  endpoint: "http://resolver.library.ualberta.ca/sfx2sirsi/data/sfxdata.xml"
  path: "data/sfx.xml"

sfx_test:
  config: "config/SolrMarc/sfx_config.properties"
  schema: marc
  path: "data/sfx.xml"

sfx_test_set:
  config: "config/SolrMarc/sfx_config.properties"
  schema: marc
  path: "spec/fixtures/sfx_test_set.xml"

symphony:
  config: "config/SolrMarc/symphony_config.properties"
  schema: marc
  path: "data/big-sample.mrc"

symphony_test_set:
  config: "config/SolrMarc/symphony_config.properties"
  schema: marc
  path: "spec/fixtures/subset.mrc"

rda_record:
  config: "config/SolrMarc/symphony_config.properties"
  schema: marc
  path: "spec/fixtures/RDA_date.mrc"

symphony_test_deletes:
  config: "config/SolrMarc/symphony_config.properties"
  schema: marc
  path: "spec/fixtures/subset_delete_first_record.mrc"

maps:
  schema: marc
  path: "data/maps.xml"

cihm:
  schema: marc
  path: "data/cihm.mrc"

curriculum:
  schema: mods
  root: "//mods:modsCollection"
  delimiter: "//mods:mods"
  namespace: '{"mods" => "http://www.loc.gov/mods/v3"}'
  vocabulary: CurriculumModsVocabulary
  mode: file
  path: "data/curriculummods.xml"

databases:
  schema: database
  root: "//databases"
  delimiter: "//hash"
  namespace: ""
  vocabulary: DatabaseVocabulary
  mode: file
  expand_path: "data/databases.xml"
  path: "data/databases.xml"
  test: false

database_test_set:
  schema: database
  root: "//databases"
  delimiter: "//hash"
  namespace: ""
  vocabulary: DatabaseVocabulary
  mode: file
  expand_path: "spec/fixtures/database_test_set.xml"
  path: "spec/fixtures/databases_test_set.xml"
  test: true

services:
  schema: services
  root: "//records"
  delimiter: "//record"
  namespace: ""
  vocabulary: PromotedServicesVocabulary
  mode: file
  path: "config/promoted_services/service_records.xml"

kule:
  schema: marc
  path: "data/kule.mrc"
  config: "config/SolrMarc/kule_config.properties"

kule_test:
  schema: marc
  path: "spec/fixtures/bmufa_rev_20181010.mrc"
  config: "config/SolrMarc/kule_config.properties"