1 : Alberta Government Library - Internet
2 : Alberta Government Library - Capital Boulevard
3 : NorQuest College - Main Building
4 : Alberta Health Services - Rockyview General Hospital
5 : NorQuest College - Westmount
6 : Alberta Health Services - Centre 15
7 : Alberta Health Services - Medicine Hat Regional Hospital
8 : Keyano College
9 : Alberta Health Services - Women's Health [in transition]
10: Alberta Health Services - Tom Baker Cancer Centre
11: Alberta Innovates - Technology Futures - Calgary
12: Alberta Innovates - Technology Futures - C-FER Technologies
13: NEOS Free Internet Resources
14: Alberta Innovates - Technology Futures - Mill Woods
15: Alberta Innovates - Technology Futures - Vegreville
16: University of Alberta Augustana
17: Covenant Health - Grey Nuns Community Hospital
18: Covenant Health - Misericordia Community Hospital
19: Alberta Health Services - Royal Alexandra Hospital
20: Alberta Health Services - Glenrose Rehabilitation Hospital
21: Concordia University of Edmonton
22: Alberta Health Services - Cross Cancer Institute
23: Burman University
24: MacEwan University - Technical Services
25: Alberta Health Services - Alberta Hospital Edmonton
26: Alberta Health Services - Centennial Centre
27: Alberta Health Services - Internet
28: Grande Prairie Regional College - Grande Prairie
29: MacEwan University - City Centre Campus
30: Alberta Health Services - QEII Hospital [in transition]
31: King's University
32: Newman Theological College
33: Olds College
34: Concordia Lutheran Seminary
35: Red Deer College
36: Vanguard College - Taylor
37: University of Alberta Archives
38: University of Alberta Book and Record Depository
39: University of Alberta Bibliotheque Saint-Jean
40: University of Alberta Winspear Business
41: University of Alberta HT Coutts Education
42: University of Alberta JW Scott Health Sciences
43: University of Alberta Rutherford-Humanities & Social Science
44: University of Alberta Internet
45: University of Alberta JA Weir Law
46: University of Alberta Cameron - Mathematics
47: Alberta Health Services - Red Deer Regional Hospital
48: University of Alberta Cameron - Science & Technology
49: University of Alberta St Joseph's College
50: University of Alberta Bruce Peel Special Collections
51: University of Alberta Bibliographic Services
52: Lakeland College Lloydminster
53: Lakeland College Vermilion
54: Grande Prairie Regional College - Fairview
55: MacEwan University - Alberta College Campus
56: MacEwan University - Centre for Arts & Communications
57: MacEwan University - Internet
58: Alberta Health Services - Alberta Children's Hospital
59: Vanguard College
60: Grande Prairie Regional College - Internet
61: Lakeland College Internet
62: Alberta Health Services - Internet
