aegeo: "Alberta Geological Survey"
aginternet: "Alberta Government Library Internet"
aglcap: "Alberta Government Library"
ahsah: "Alberta Health Services Alberta Hospital Edmonton"
ahsahe: "Alberta Health Services Alberta Hospital Edmonton"
ahscenten: "Alberta Health Services Centennial Centre"
ahserc: "Alberta Health Services Education Resource Centre"
ahsmhrh: "Alberta Health Services Medicine Hat Regional Hospital"
ahsqeii: "Alberta Health Services Queen Elizabeth II Hospital"
ahsrah: "Alberta Health Services Royal Alexandra Hospital"
ahsreddr: "Alberta Health Services Red Deer Regional Hospital"
ahssturg: "Alberta Health Services SturgeonIn TransitionExpect Delays"
ahsplc: "Alberta Health Services Peter Lougheed Centre"
ahsrvgh: "Alberta Health Services Rockyview General Hospital"
ahstbcc: "Alberta Health Services Tom Baker Cancer Centre"
ahswhc: "Alberta Health Services Women's Health Centre Alberta Children's Hospital"
ahsach: "Alberta Health Services Alberta Children's Hospital"
ahsctr15: "Alberta Health Services Centre 15"
ahsctr: "Alberta Health Services Centre 15"
15: "Alberta Health Services Centre 15"
ahscross: "Alberta Health Services Cross Cancer Institute"
ahs_int: "Alberta Health Services Internet"
ahsglenrse: "Alberta Health Services Glenrose Rehabilitation Hospital"
ahsglenrs: "Alberta Health Services Glenrose Rehabilitation Hospital"
aitfcalg: "Alberta Innovates Technology Futures Calgary"
aitfc-fer: "Alberta Innovates Technology Futures CFer Technologies"
aitfcfer: "Alberta Innovates Technology Futures CFer Technologies"
aitfmw: "Alberta Innovates Technology Futures Mill Woods"
aitfveg: "Alberta Innovates Technology Futures Vegreville"
aitfdevon: "Alberta Innovates Technology Futures Devon"
concordia: "Concordia University of Edmonton"
concordsem: "Concordia Lutheran Seminary"
covenantgn: "Covenant Health Grey Nuns Community Hospital"
covenantmh: "Covenant Health Misericordia Community Hospital"
cross: "Alberta Health Services Cross Cancer Institute"
cuc: "Burman University"
burman: "Burman University"
gprc: "Grande Prairie Regional College"
gprcfrvw: "Grande Prairie Regional College Fairview"
gprcgp: "Grande Prairie Regional College Grande Prairie"
gprcint: "Grande Prairie Regional College Internet"
grmacacc: "MacEwan University Alberta College Campus"
grmaccac: "MacEwan University Centre for Arts & Communications"
grmacint: "MacEwan University Internet"
grmacsoc: "MacEwan University South CampusOn the MoveExpect Delay"
grmactsv: "MacEwan University Technical Services"
grmacewan: "MacEwan University City Centre Campus"
justiceca: "Justice Canada"
keyano: "Keyano College"
king: "King's University"
kings: "King's University"
lakelndl: "Lakeland College Lloydminster"
lakelndll: "Lakeland College Lloydminster"
lakelndin: "Lakeland College Internet"
lakelndvr: "Lakeland College Vermilion"
neosfree: "NEOS Free Internet Resources"
neosfre: "NEOS Free Internet Resources"
newman: "Newman Theological College"
norqmain: "Norquest College Main Building"
norqwest: "Norquest College Westmount"
old: "Olds College"
olds: "Olds College"
reddeerc: "Red Deer College"
taylor: "Vanguard College Taylor"
uaarchiv: "University of Alberta Archives"
uaarchives: "University of Alberta Archives"
uaaug: "University of Alberta Augustana"
uabard: "University of Alberta Book and Record Depository"
uabsj: "University of Alberta Bibliotheque SaintJean"
uabusi: "University of Alberta Winspear Business"
uabusiness: "University of Alberta Winspear Business"
uaeduc: "University of Alberta HT Coutts Education"
uahlthsc: "University of Alberta JW Scott Health Sciences"
uahss: "University of Alberta Rutherford Humanities & Social Science"
uainternet: "University of Alberta Internet"
ualaw: "University of Alberta JA Weir Law"
uamath: "University of Alberta Cameron Mathematics"
uascitech: "University of Alberta Cameron Science & Technology"
uasjc: "University of Alberta St Joseph's College"
uaspcol: "University of Alberta Bruce Peel Special Collections"
uaspcoll: "University of Alberta Bruce Peel Special Collections"
uatechserv: "University of Alberta Bibliographic Services"
vanguard: "Vanguard College"
