# until https://github.com/ualbertalib/discovery/issues/422 is addressed changes
# to this file should be mirrored in config/SolrMarc/index_scripts/location_facet.bsh
aegeo:  Alberta Geological Survey
aginternet: Alberta Government Library - Internet
aglcap:  Alberta Government Library - Capital Boulevard
aglcom:  Alberta Government Library - Commerce Place
aglgwl:  Alberta Government Library - Great West Life
agllb: Alberta Government Library - Labour Building
aglmnc:  Alberta Government Library - Monenco Bldg Calgary
aglncc:  Alberta Government Library - Neil Crawford Centre
aglssp:  Alberta Government Library - 107 Street
agltpn:  Alberta Government Library - Telus Plaza North
ahsach: Alberta Health Services - Alberta Children's Hospital
ahsahe: Alberta Health Services - Alberta Hospital Edmonton
ahscenten: Alberta Health Services - Centennial Centre
ahsctr15: Alberta Health Services - Centre 15
ahskec: Alberta Health Services - Kaye Edmonton Clinic
ahsrah:  Alberta Health Services - Royal Alexandra Hospital
ahsreddr: Alberta Health Services - Red Deer Regional Hospital
ahsrvgh: Alberta Health Services - Rockyview General Hospital
ahssturg: Alberta Health Services - Sturgeon Community Hospital
ahstbcc: Alberta Health Services - Tom Baker Cancer Centre
ahserc: Alberta Health Services
ahscenten: Alberta Health Services
ahsint: Alberta Health Services/Covenant Health - Internet
ahsglenrse: Alberta Health Services - Glenrose Rehabilitation Hospital
aitfcalg:  Alberta Innovates - Technology Futures - Calgary
aitfcfer: Alberta Innovates - Technology Futures - C-FER Technologies
aitfc-fer: Alberta Innovates - Technology Futures - C-FER Technologies
aitfdevon: Alberta Innovates - Technology Futures - Devon
aitfmw: Alberta Innovates - Technology Futures - Mill Woods
aitfveg: Alberta Innovates - Technology Futures - Vegreville
burman: Burman University
concordia:  Concordia University of Edmonton
concordsem: Concordia Lutheran Seminary
covenantgn: Covenant Health - Grey Nuns Community Hospital
covenantmh: Covenant Health - Misericordia Community Hospital
cross:  Cross Cancer Institute
cuc:  Canadian University College
gprcgp: Grande Prairie Regional College - Grande Prairie
gprcfrvw: Grande Prairie Regional College - Fairview
gprcint: Grande Prairie Regional College - Internet
grmacacc: Grant MacEwan University - Alberta College Campus
grmaccac: Grant MacEwan University - Centre for Arts & Communications
grmacint: Grant MacEwan University - Internet
grmactsv: Grant MacEwan University - Technical Services
grmacsoc: Grant MacEwan University - South Campus
grmacewan: Grant MacEwan University - City Centre Campus
justiceca: Justice Canada
keyano: Keyano College
kings:  The King's University College
lakelndin: Lakeland College Internet
lakelndll: Lakeland College Lloydminster
lakelndvr: Lakeland College Vermilion
neosfree: NEOS Free Internet Resources
newman: Newman Theological College
nlcgr: Northern Lakes College - Grouard
nlcint: Northern Lakes College - Internet
nlcsl: Northern Lakes College - Slave Lake
norqmain: NorQuest College - Main Building
norqwest: NorQuest College - Westmount
olds: Olds College
reddeerc: Red Deer College
taylor: Taylor College and Seminary
vanguard: Vanguard College
uaarchives: University of Alberta Archives
uaaug: University of Alberta Augustana
uabard: University of Alberta Research and Collections Resource Facility
uabsj: University of Alberta Bibliotheque Saint-Jean
uabusiness: University of Alberta Winspear Business
uaeduc: University of Alberta HT Coutts Education
uahlthsc: University of Alberta JW Scott Health Sciences
uahss:  University of Alberta Rutherford-Humanities & Social Science
uainternet: University of Alberta Internet
ualaw: University of Alberta JA Weir Law
uamath: University of Alberta Mathematics
uascitech: University of Alberta Cameron - Science & Technology
uasjc:  University of Alberta St Joseph's College
uaspcoll: University of Alberta Bruce Peel Special Collections
uatechserv: University of Alberta Bibliographic Services
uarcrf: University of Alberta Research and Collections Resource Facility
usic tech lab: University of Alberta Cameron - Science & Technology - Lab
