ag_bus_dev: "agricultural business development branch, olds"
ag_tech: "agricultural technology centre, lethbridge"
agdex: "agdex collection"
ahfmr: "alberta heritage foundation for medical research"
annualrept: "annual reports"
archives: "archives"
art_cat: "exhibition catalogues"
atc: "academic technologies centre"
atlas: "atlases"
atlas_os: "atlas oversize"
atlasarcve: "atlas archives"
avail_nh: "see link above"
avail_soon: "available soon"
biblio: "bibliography collection"
bindery: "bindery"
binderyspc: "Off-site Book Restoration"
bison_elk: "bison and elk centres, leduc"
borealwood: "boreal wood centre"
cait: "centre for agri-industrial technology"
calendars: "calendars"
canc_order: "cancelled order"
capsites: "cap sites"
cataloging: "being catalogued"
ccbcc: "canadian children's book centre collection"
cdc_south: "crop diversification centre, brooks"
checkedout: "checked out"
chinese: "chinese collection"
circ_desk: "circulation desk"
closestack: "closed stacks"
curmediaos: "curriculum media oversize"
curr_auth: "curriculum authorized"
curr_fre: "curriculum french collection"
curr_guide: "curriculum guides"
curr_hist: "curriculum historical collection"
curr_media: "curriculum media"
curr_micro: "curriculum micromaterials"
curr_over: "curriculum oversize"
corr_ref: "curriculum reference"
currentper: "current periodicals"
currgdhist: "curriculum guides historical collection"
curric_ya: "curriculum ya fiction"
curriculum: "curriculum"
currmdhist: "curriculum media historical"
data: "data library"
data_ref: "data reference"
dept_loan: "department loan"
discard: "withdrawn"
display: "topical displays"
distance: "distance education materials-esl"
dvd: "dvd collection"
easy_read: "easy reading collection"
electrical: "electrical - fairview college/grande prairie site"
esl: "english as a second language"
ethics: "ethics collection"
facultypub: "faculty publications"
feature: "topics related to post-secondary education"
fiction: "fiction"
field_crop: "field crops branch, lacombe"
floor_1: "floor 1"
floor_2: "floor 2"
floor_3: "floor 3"
floor_4: "floor 4"
food_proc: "food processeing centre, leduc"
fort_chip: "fort chipewyan"
german: "german collection"
govpub: "government publications"
gov_info: "government information"
graphic: "graphic novel"
heritage: "heritage"
holds: "on hold"
horse_ind: "horse industry branch, calgary"
ill: "on loan to another library"
ill_: "on loan to another library"
in_process: "in process"
indexes: "indexes"
info_desk: "information desk"
inprocess: "being catalogued"
inshipping: "being shipped to destination"
internet: "internet"
intransit: "in transit"
ir_office: "institutional research office"
javitch: "javitch special collection"
juvenile: "juvenile collection"
kscentre: "keyano college skill centre"
lab: "lab"
legal: "legal"
leisure: "leisure reading"
libuse: "unavailable"
longoverdue: "items long overdue"
lost: "lost"
lost-assum: "assumed lost"
lost-claim: "claims lost"
lost-paid: "lost and paid for"
m_family: "marital and family studies"
mainstacks: "main stacks"
map_arch_o: "map archive oversize"
map_archve: "map archives"
map-cabt: "map cabinet"
map-os: "map oversize"
map_os: "map oversize"
map-ref: "map reference"
map_ref: "map reference"
map_stack: "map stacks"
maps: "maps"
media: "media"
micro_ref: "microforms reference"
microfiche: "microfiche"
microfilm: "microfilm"
microform: "microforms"
micropaque: "micro-opaque"
missing: "missing"
music: "music"
music_cd: "music cd"
misc_indx: "music indexes"
music_lp: "music lp record"
music_mini: "music miniature scores"
music_os: "music oversize"
music_part: "music chamber ensemble/opera workshop"
music_ref: "music reference"
music_res: "music reserve"
musiclosed: "music closed stacks"
musicmedia: "music media"
newreceipt: "music new receipt"
newspapers: "newspapers"
niosh: "niosh reports"
north_1: "north 1"
north_2: "north 2"
north_3: "north 3"
north_4: "north 4"
north_5: "north 5"
nursng_res: "nursing reserve"
off_campus: "off campus resource - ask for assistance"
office: "office"
on_shelf: "on shelf"
on_the_fly: "on the fly"
on-order: "on order"
on-order-h: "on order - holdable"
over_flat: "oversize flat"
oversize: "oversize"
pamphlet: "pamphlets"
paperbacks: "paperbacks"
parish: "parish services"
patfamcoll: "patient family collection"
patristic: "patristic literature"
periodical: "periodicals"
polar: "circumpolar"
polar_cab: "polar cabinet"
polar_micr: "circumpolar microforms"
polar_os: "circumpolar oversize"
polar_pamp: "circumpolar pamphlets"
polar_per: "circumpolar periodicals"
polar_ref: "circumpolar reference"
polaratlas: "circumpolar atlases"
prcc: "peace river correctional centre"
ref_aux: "reference auxiliar"
reference: "reference"
regulatory: "regulatory"
repair: "being repaired"
reserves: "reserve desk"
sec_stacks: "secondary stacks"
south_1: "south 1"
south_1a: "south 1a"
south_2: "south 2"
south_2a: "south 2a"
specialcol: "special collections"
st_albert: "st. albert"
stacks: "standard shelving location"
stacks_: "on shelf"
standards: "standards"
statistics: "statistics"
stor_dark: "dark storage - non-circulation"
storage: "storage"
studyguide: "guides for composition, grammar, etc."
sust_agric: "sustainable agriculture resource centre"
tecdsk_res: "technology helpdesk reserve"
tech_desk: "technology desk"
theses: "theses"
trad_med: "traditional medicine"
trades: "trades"
trades_sa: "trades - st. albert"
unknown: "unknown"
videos: "videos"
readonsite: "Read On Site"
